### ISSUE TITLE
Is this merge still happening?

### ISSUE THREAD

**Issue by iam3yal** [underdash/underdash#11]
I would really love to have this merge! hopefully it's still a thing!

Learning lodash and underscore is painful especially for new developers and even experienced developers that need to work on different project where one uses lodash and the other underscore, sometimes I can convince people to move into lodash but at times it's not possible when people just are too _used_ to a library and won't agree to move to another.

I really, really hope that both communities will join and do/create something even better/greater! ;)

**Comment by jdalton** [comment]
Thanks! Work on lodash v4 which proofs out several of underdash goals is still ongoing. I expect a bit more conversation once it's released.

**Comment by eyalsk** [comment]
Thank you. :)
