### ISSUE TITLE
Is the merge still taking place?

### ISSUE THREAD

**Issue by aayushkapoor206** [underdash/underdash#13]
Wanted to know if there will ever be underdash!

**Comment by jridgewell** [comment]
https://github.com/underdash/underdash/issues/12

**Comment by jdalton** [comment]
Yep still working on it

<img height=75% width=75% src="https://cloud.githubusercontent.com/assets/4303/11190706/f60272d0-8c4b-11e5-8564-72e69497e87a.png">
<img width=75% height=75% src="https://cloud.githubusercontent.com/assets/4303/11190708/f7a86770-8c4b-11e5-818a-817e9bf819ef.png">

Lodash v4, which proofs out many of the merge details, is scheduled for release Jan 12-16 2016.

**Comment by aayushkapoor206** [comment]
Whoa! That's awesome. Thanks for the reply @jdalton :+1:
