### ISSUE TITLE
Release retrospective.

### ISSUE THREAD

**Issue by jdalton** [underdash/underdash#15]
While Lodash v4 proofed out many of the ideas from our merge discussions. There's still some things to do, tweak, and change for the next iteration. This can be the place to discuss it. \cc @megawac.

**Comment by megawac** [comment]
As John knows, I have several concerns on the direction of several api changes in v4. While there has been merit to many of these ideas, some I feel have been against the spirit of both libraries.

I'll elaborate on this comment when I get a chance.

**Comment by jdalton** [comment]
On more procedure related things I think having an RC release the next go will help shake out some bugs before going to the next major bump. I know nothing gets as much attention as a major bump but I think an RC or two, like we did with v1, could help reduce the amount of bug reports right after a major bump.

**Comment by rattrayalex** [comment]
@megawac circling back on this, are your thoughts available anywhere?

**Comment by jdalton** [comment]
It's been over a year so maybe this issue is a bit stale. Since the v4 release it's gone on to become in the top 3 most depended upon packages in npm so things have worked out for it.

**Comment by rattrayalex** [comment]
Cool. I'm planning on including it as the stdlib of [LightScript](http://lightscript.org) so wanted to check that I wouldn't regret using v4 as the default.
