### ISSUE TITLE
TC39 proposal: Object.keysIn, Object.valuesIn, Object.entriesIn.

### ISSUE THREAD

**Issue by jdalton** [underdash/underdash#16]
Recently the TC39 agreed to remove [Reflect.enumerate](http://www.ecma-international.org/ecma-262/6.0/#sec-reflect.enumerate). However that was the only way to provide a [shimmable compat path for older environments](https://github.com/tc39/ecma262/commit/d96e60a99a40fab2de0df329b3e5445ac27b8a8e) which is used by [_.forIn](https://lodash.com/docs#forIn), [_.keysIn](https://lodash.com/docs#keysIn), and friends.

Leo Balter and Rick Waldron (TC39 rep) of the jQuery Foundation, which Lodash is apart of, have a [draft proposal](https://github.com/leobalter/object-keysin-valuesin-entries-in) to add `Object.keysIn`, `Object.valuesIn`, and `Object.entriesIn`. These are based roughly on Lodash's [_.keysIn](https://lodash.com/docs#keysIn), [_.valuesIn](https://lodash.com/docs#valuesIn), and [_.toPairsIn](https://lodash.com/docs#toPairsIn) and would fill the `Reflect.enumerate` shim gap.

Feedback on them would be appreciated. Let's keep spec discussion to [Leo's repo](https://github.com/leobalter/object-keysin-valuesin-entries-in) and any Lodash/Underscore lib related side-bar discussions here.

**Comment by jdalton** [comment]
I think we should add an alias `entries` for `pairs`/`toPairs` to Underscore/Lodash since that seems to be the way [they're going](https://github.com/tc39/proposal-object-values-entries)

**Comment by jdalton** [comment]
@paulfalgout Would you be up for creating the PRs to add the aliases?

**Comment by paulfalgout** [comment]
I'd love to.. however at the moment I've overbooked myself. I'm currently procrastinating from an online course I'm taking. I'll be done in May and am very interested in contributing more and in more places. Enjoyed listening to JS Air this week BTW. Come summer, I'll bother you about what I can help with :wink:

**Comment by jdalton** [comment]
> I'd love to.. however at the moment I've overbooked myself.

No worries.

> Come summer, I'll bother you about what I can help with :wink:

Rock!

**Comment by jdalton** [comment]
I added the entries aliases at https://github.com/lodash/lodash/commit/6bef0c3f56c6797a065c2752b32627c10b197f97.

**Comment by jdalton** [comment]
We'll be championing these additions at the next TC39 meeting.

**Comment by jdalton** [comment]
This spec has been rejected by the TC39. The `for..in` is considered bad legacy.
