### ISSUE TITLE
Extend and Assign

### ISSUE THREAD

**Issue by megawac** [underdash/underdash#2]
Another incompatibility which should be shelled out is `extend` and `assign`

In lodash these are aliases (`own` behaviour) while in underscore `extend` iterates `in` keys and `assign` uses `own` properties

I favour underscore's implementation in this front as I occasionally want the selection

**Comment by jashkenas** [comment]
I think that `extend` for all keys and `assign` for own keys is nice, and helps with upgrading. It's nice to have the choice. The downside is the namesquatting on `extend`, which would otherwise be useful for a great many other things.

**Comment by jdalton** [comment]
Closed by #14.
