### ISSUE TITLE
Contrib functions

### ISSUE THREAD

**Issue by jridgewell** [underdash/underdash#7]
I did a scan of the underscore contrib functions last night. Of all of them, the ones I've found useful are:
- `chunk` (https://github.com/jashkenas/underscore/pull/1919, implemented in lodash)
- `conjoin` and `disjoin` (https://github.com/jashkenas/underscore/pull/2124, https://github.com/lodash/lodash/issues/1072)
- `fromQuery` (I've implemented this a handful of times)
- `toQuery` (`$.param`, but would complement `fromQuery`)

Any others you've found useful?

**Comment by jashkenas** [comment]
Realy? That's it?

I was thinking more along the lines of `require("underdash/contrib")` including most of them, or perhaps more than half.

But if it's going to just be a handful, maybe they go into "more", and we leave Underscore-Contrib alone.

**Comment by jdalton** [comment]
At the moment -contrib doesn't meet the quality bar of lodash. If we take it on it means putting it through the same ringer, modularizing, getting test coverage up, testing across all supported environments. It's a bit much for something that's been a bit of a dumping ground for odds and ends. I'm fine leaving it as it's own package (if it's modularized on its own that's fine).

**Comment by jashkenas** [comment]
Alright then. Let's maybe pull a handful of our favorite methods for "more", and leave the rest of it as it stands.

We can use this ticket to nominate favorite contrib functions, if any.

**Comment by megawac** [comment]
I find `weave` & `interpose` potentially useful. `splat` and `unsplat` may be worth refining as well (https://github.com/lodash/lodash/issues/756) (with index support)

**Comment by jdalton** [comment]
Closed by #14.
