### ISSUE TITLE
Opportunity for chainable functions?

### ISSUE THREAD

**Issue by thom-nic** [underdash/underdash#9]
So I realize this is a markedly different approach from both underscore and lodash, but wondering if anyone has given consideration to a chain-able/ fluent API similar jquery or [trine](https://github.com/jussi-kalliokoski/trine/).

I'll admit the first time I used underscore and lodash I (naively) assumed they would work this way, e.g. the returned result has the API methods baked in a la jquery.

**Comment by CrossEye** [comment]
I wouldn't expect this merger to be the time or the place to take on such a radical reformulation of the design of the libraries.  The idea is to work with what they have in common.

**Comment by jridgewell** [comment]
We have `_.chain` for this, and lodash takes it a step further with implicit chaining `_`:

```js
// Underscore and lodash
_.chain([1, 2, 3]).filter((i) => i > 1).each(doSomething);

// lodash
_([1, 2, 3]).filter((i) => i > 1).each(doSomething);

**Comment by thom-nic** [comment]
Hey cool I wasn't aware of either of those.  +1 for keeping the lodash chaining style in underdash.

**Comment by jmdevivo** [comment]
I agree, lodash style chaining would be convenient in the merger. It seems
more intuitive than the chain method (which could also be kept for least
reasons if it isn't very big)

**Comment by jmeas** [comment]
tbh I think there are much more important API questions to be discussed. Chaining is the least of my concerns when it comes to this potential merge.
